#!/bin/bash
set -e
echo "[*] HyperPredict Device Adapter & Code Stripper"

if command -v adb &>/dev/null; then
    CPUINFO=$(adb shell "cat /proc/cpuinfo | grep -m1 Hardware")
    TOPOLOGY=$(adb shell "ls /sys/devices/system/cpu/ | grep -E 'cpu[0-9]+$' | tr '\n' ' '")
    FREQS=$(adb shell "cat /sys/devices/system/cpu/cpufreq/policy0/scaling_available_frequencies")
    THERMAL=$(adb shell "ls /sys/class/thermal/ | grep -c thermal_zone || echo 0")
    DEVFREQ=$(adb shell "ls /sys/class/devfreq/ 2>/dev/null | grep -c gpu || echo 0")
else
    CPUINFO=$(grep -m1 Hardware /proc/cpuinfo 2>/dev/null || echo "ARM64 Device")
    TOPOLOGY=$(ls /sys/devices/system/cpu/ | grep -E 'cpu[0-9]+$' | tr '\n' ' ')
    FREQS=$(cat /sys/devices/system/cpu/cpufreq/policy0/scaling_available_frequencies 2>/dev/null || echo "800000 1200000 1800000 2400000 3000000")
    THERMAL=$(ls /sys/class/thermal/ | grep -c thermal_zone 2>/dev/null || echo 0)
    DEVFREQ=$(ls /sys/class/devfreq/ 2>/dev/null | grep -c gpu || echo 0)
fi

cat > include/device/hardware.h << EOF
#pragma once
/* AUTO-GENERATED BY device_probe.sh - DO NOT EDIT */
#define SOC_NAME "${CPUINFO##*: }"
#define CPU_CLUSTER_COUNT 3
#define LITTLE_CORES {0,1,2,3}
#define MID_CORES {4,5}
#define BIG_CORES {6,7}
#define HAS_DEVFREQ_GPU $DEVFREQ
#define THERMAL_ZONE_COUNT $THERMAL
#define BASELINE_FREQS {$(echo $FREQS | tr ' ' ',')}
#define POWER_MODEL_INIT {1.2e-9, 0.0045, 0.75}
#define DEVICE_ADAPTED 1
EOF
echo "[✓] Device profile generated: include/device/hardware.h"